version: '3.8'

services:
  # --- Frontend Web App ---
  web:
    image: scythe504/fluxstream-web:latest
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://api:8080
    ports:
      - "3000:3000"
    networks:
      - fluxstream
    depends_on:
      - api
    restart: unless-stopped
  # --- Backend API ---
  api:
    image: scythe504/fluxstream-api:latest
    environment:
      - PORT=8080
      - APP_ENV=local
      - PUBLIC_URL=http://localhost:8080
      - REDIS_DB_ADDRESS=redis
      - REDIS_DB_PORT=6379
      - REDIS_DB_PASSWORD=
      - REDIS_DB_DATABASE=0
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=fluxstream
      - DB_USERNAME=fluxstream
      - DB_PASSWORD=fluxstream
      - DB_SCHEMA=public
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "8080:8080"
    volumes:
      - "{{DOWNLOAD_PATH}}:/app/fluxstream/download"
    networks:
      - fluxstream
    restart: unless-stopped
# --- Networks & Volumes ---
networks:
  fluxstream: